### ISSUE TITLE
item需要点击两次才能响应

### ISSUE THREAD

**Issue by zarvin** [zhuguohui/HorizontalPage#1]
滑动翻页后，点击item需要点两次才会弹出提示，第一次没反应。不知您有没有发现这个问题？
我检查了一下好像是在动画执行完成之后，recyclerview的scrollstate没有恢复成idle

**Comment by zhuguohui** [comment]
我没注意到这个问题

**Comment by moonljt521** [comment]
这个问题解决了么

**Comment by hxunan** [comment]
@zarvin 确实是啊，你有什么思路解决吗？

**Comment by xxyandroid** [comment]
在动画回调onAnimationEnd 这个方法 中设置recyclerview   scrollstate 。mRecyclerView.stopScroll();能解决

**Comment by simline** [comment]
@xxyandroid 设置后的效果是，整体滑动更乱了，BUG 依然存在。。。 @zhuguohui

**Comment by hxunan** [comment]
@simline 对的，设置了之后，滑动超过两页就出问题了

**Comment by LockZhao** [comment]
@BigXiangxy  @simline @hxunan   看了下源码，@BigXiangxy 的方法设置mRecyclerView.stopScroll();之后，会让OnTouchListener的回调失效，下次触摸时无法刷新startX的值，造成getStartPageIndex()方法返回始终为0。需要在mRecyclerView.stopScroll()之后手动刷新：startY = offsetY; startX = offsetX;

**Comment by shawn-lam** [comment]
不知道为什么博主需要使用动画来进行scrollBy，其实直接使用smoothScrollBy可以解决网友说的大多数问题，而且代码非常简单，在onScrollStateChanged也不需要借助于OnFlingListener，最近会提供相关的代码，如果要自己布局的话LayoutManager都不需要，只要一个Helper几十行代码就可以实现分页了

**Comment by LinBinghe** [comment]
不知道为什么博主需要使用动画来进行scrollBy，其实直接使用smoothScrollBy可以解决网友说的大多数问题，而且代码非常简单，在onScrollStateChanged也不需要借助于OnFlingListener，最近会提供相关的代码，如果要自己布局的话LayoutManager都不需要，只要一个Helper几十行代码就可以实现分页了

**Comment by SearchSunny** [comment]
去除holder.itemView.setOnClickListener()或Adapter.setOnItemClickListener()，增加recyclerView.addOnItemTouchListener(自定义实现RecyclerView.OnItemTouchListener)事件，可解决item需要点击两次才能响应的问题。

**Comment by kkyflying** [comment]
@SearchSunny 如果你这样设置的话，就会导致你无法点击item中的子控件了

**Comment by may7be** [comment]
当只有一页，左右使劲滑动多次，必然会崩溃。
HorizontalPageLayoutManager执行到recyclerAndFillItems()的Rect.intersects(diaplagRect, childRect)时会报空指针异常。
作者能看看为什么吗？

**Comment by woomartin** [comment]
依然存在这个问题,打印日志发现,执行adapter.notifydatachanged()时,有时并不会刷新其他页面的item.需要在翻页时再次刷新item

**Comment by hyxi** [comment]
rvList.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
                super.onScrollStateChanged(recyclerView, newState);
            }

            @Override
            public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                if (dy > 0) {
                    LinearLayoutManager linearLayoutManager = (LinearLayoutManager) recyclerView.getLayoutManager();
                    int visibleItemCount = linearLayoutManager.getChildCount();
                    int totalItemCount = linearLayoutManager.getItemCount();
                    int pastVisibleItems = linearLayoutManager.findFirstVisibleItemPosition();

                    if ((visibleItemCount + pastVisibleItems) >= totalItemCount) {
                        if (!rvList.canScrollVertically(1)) {
                            rvList.stopScroll();
                        }
                    }
                }
            }
        });

这样可以解决
